language: rust

rust:
  - nightly

    
os:
  - linux
  - osx

before_script:
  - rustup component add rustfmt-preview      
  - rustup component add rust-src
  - (test -x $HOME/.cargo/bin/cargo-install-update || cargo install cargo-update)
  - (test -x $HOME/.cargo/bin/xargo || cargo install xargo)
  - (test -x $HOME/.cargo/bin/bootimage || cargo install bootimage)
  - cargo install-update -a

script:
  - cargo test
  - bootimage build --target intermezzos
  - cargo fmt -- --write-mode=diff

cache:
  directories:
    - $HOME/.cargo
    - $HOME/.xargo
    - $TRAVIS_BUILD_DIR/target
