language: rust

rust:
  - nightly

    
os:
  - linux
  - osx

cache:
  - cargo

before_install:
  - rustup component add rustfmt-preview      
  - which xargo || cargo install xargo

script:
  - cargo test
  - cargo fmt -- --write-mode=diff
