sudo: required
dist: trusty
language: rust
rust:
  - nightly-2016-05-26
script:
  - cd chapter_03/3.1-headers && make build && cd -
  - cd chapter_03/3.2-hello-world && make build && cd -
  - cd chapter_03/3.3-iso && make build && cd -
  - cd chapter_03/3.4-qemu && make build && cd -
  - cd chapter_03/3.5-make && make build && cd -
  - cd chapter_04/4.1-paging && make build && cd -
  - cd chapter_04/4.2-setting-up-a-gdt && make build && cd -
  - cd chapter_04/4.3-jumping-headlong-into-long-mode && make build && cd -
  - cd chapter_05 && make build && cd -
  - cd src && make && make test

addons:
  apt:
    packages:
      - nasm
